# Generated by Django 5.0.4 on 2024-05-31 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_like',
            field=models.BooleanField(default=False),
        ),
    ]
